### PR TITLE
moves to "master" build

### PR DESCRIPTION
**Pull request by nathandunn**
I'm still testing this, but this build off of 2.0.3.  I'll put another tagged image up on dockhub.  GMOD/Apollo:latest once I confirm that this is working.  

This is more for reference.

### CODE REVIEW

**Comment by erasche** [comment]
missed this, so sorry.

building from master can be tricky. 

- people building images locally will just have a cached version, until they tell docker to build without a cache
- docker then ignores the cache for all steps, even possibly expensive ones that came before the git clone/wget
- thus many people choose to use git hashes to produce reproducible builds + ensure that the cache gets busted at the right place and the right time.

**Comment by erasche** [comment]
Pursuant to above points, would personally move the wget below the apt-gets in order to cache the apt-gets which change much less frequently than the apollo codebase.

**Comment by nathandunn** [comment]
@erasche   I had done this on purpose as I was trying to fix the build to use master and rebuild until I got something working.  

Absolutely agree that a hash is the way to go.

**Comment by erasche** [comment]
Ah gotcha, that wasn't obviously immediately. Makes sense!

**Comment by nathandunn** [comment]
@erasche  And also WRT to the apt-get order, wget below the apt-get makes sense for production.   Feel free to move back when you think its ready.

**Comment by erasche** [comment]
@nathandunn I'll pull in the bits that are appropriate for me, especially since gmod/docker-apollo will be the future home of this image.

**Comment by nathandunn** [comment]
Sounds good. 

Nathan

**Pull request merged**
